### ISSUE TITLE
Missing import in operations.py

### ISSUE THREAD

**Issue by DGonzalezPicos** [Hoeijmakers/tayph#100]
The tayph routine would not work because it was missing an import traced down to operations.py function: `normalize_orders`. The issue was fixed by simply importing the function `notnegativetest` in line 209 with the rest of tayph.vartests.

**Comment by Hoeijmakers** [comment]
Thank you. This has just been fixed and pushed. Please pull the current version.

Also please be advised that we are continuously working on Tayph, sometimes introducing a bug like this. If the code turns out stable after this fix, please keep an eye on the commits we do before pulling. I'll try to keep the number of commits small and significant, and test more before pushing, but things may slip through the cracks.

Thanks!
